#kafka配置信息
kafka:
  #bootstrap-servers: 192.168.56.101:9092,192.168.56.101:9093,192.168.56.101:9094
  bootstrap-servers: 192.168.0.135:9092
  producer:
    batch-size: 16785                                   #一次最多发送数据量
    retries: 1                                          #发送失败后的重复发送次数
    buffer-memory: 33554432                             #32M批处理缓冲区
    linger: 1
  consumer:
    auto-offset-reset: latest                         #最早未被消费的offset
    group-id: groud-v1
    max-poll-records: 500                              #批量消费一次最大拉取的数据量
    enable-auto-commit: false                           #是否开启自动提交
    auto-commit-interval: 1000                          #自动提交的间隔时间
    session-timeout: 6000                               #连接超时时间
    max-poll-interval: 2000                             #手动提交设置与poll的心跳数
  listener:
    batch-listener: false                                #是否开启批量消费，true表示批量消费
    concurrency: 1                                      #设置消费的线程数
    poll-timeout: 1500                                  #自动提交设置，如果消息队列中没有消息，等待timeout毫秒后，调用poll()方法。如果队列中有消息，立即消费消息，每次消费的消息的多少可以通过max.poll.records配置。
    topics: test-topic

logging:
   path: D:/target/logs-v1